version: '2'

services:
  isb-api-backend-landindpage:
    container_name: isb-api-backend-landindpage
    image: isb-api-backend-landindpage:0.0.0.1
    build: .
    ports:
      - 1101:1101
    restart: always